"""Fetching the original subscription, with HWID headers rewritten."""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field

import httpx

from .config import Settings

#: Remnawave ≥ 2.9.0 validates the incoming header against exactly this shape and
#: silently ignores anything else, so it is worth surfacing in the admin UI.
HWID_RE = re.compile(r"^[a-zA-Z0-9=-]{10,64}$")

HWID_MODES = ("override", "fallback", "passthrough")

#: Request headers worth carrying upstream. Anything not listed is dropped so the
#: panel sees a clean request instead of our own hop's noise.
FORWARD_REQUEST_HEADERS = (
    "user-agent",
    "accept",
    "accept-language",
    "accept-encoding",
    "x-device-os",
    "x-ver-os",
    "x-device-model",
)

#: Response headers clients actually read. Everything else is regenerated by us.
FORWARD_RESPONSE_HEADERS = (
    "subscription-userinfo",
    "profile-title",
    "profile-update-interval",
    "profile-web-page-url",
    "support-url",
    "announce",
    "announce-url",
    "routing",
    "content-disposition",
    "x-provider-id",
    "x-hwid-active",
    "x-hwid-not-supported",
    "x-hwid-max-devices-reached",
    "x-hwid-limit",
)


def hwid_is_valid(value: str | None) -> bool:
    return bool(value) and bool(HWID_RE.match(value or ""))


@dataclass(slots=True)
class HwidPlan:
    """What we decided to do about the client's HWID, ready for the log."""

    hwid_in: str | None
    hwid_sent: str | None
    action: str  # replaced | added | kept | none


def plan_hwid(mode: str, configured: str | None, incoming: str | None) -> HwidPlan:
    incoming = (incoming or "").strip() or None
    configured = (configured or "").strip() or None

    if mode == "passthrough" or not configured:
        return HwidPlan(incoming, incoming, "kept" if incoming else "none")
    if mode == "fallback":
        if incoming:
            return HwidPlan(incoming, incoming, "kept")
        return HwidPlan(incoming, configured, "added")
    # override
    return HwidPlan(incoming, configured, "replaced" if incoming else "added")


@dataclass(slots=True)
class UpstreamResult:
    status_code: int
    text: str
    headers: dict[str, str]
    elapsed_ms: int
    content_type: str
    bytes_in: int


@dataclass(slots=True)
class UpstreamRequest:
    url: str
    client_headers: dict[str, str]
    hwid_plan: HwidPlan
    device_os: str | None = None
    device_ver: str | None = None
    device_model: str | None = None
    user_agent_override: str | None = None
    extra_headers: dict[str, str] = field(default_factory=dict)

    def build_headers(self) -> dict[str, str]:
        lowered = {k.lower(): v for k, v in self.client_headers.items()}
        headers: dict[str, str] = {}
        for name in FORWARD_REQUEST_HEADERS:
            value = lowered.get(name)
            if value:
                headers[name] = value
        # Never ask for a compressed body we would then have to decode by hand;
        # httpx handles gzip/deflate/br itself when we let it choose.
        headers.pop("accept-encoding", None)

        if self.user_agent_override:
            headers["user-agent"] = self.user_agent_override
        headers.setdefault("user-agent", "subremuxer")

        if self.hwid_plan.hwid_sent:
            headers["x-hwid"] = self.hwid_plan.hwid_sent
        else:
            headers.pop("x-hwid", None)

        for header, value in (
            ("x-device-os", self.device_os),
            ("x-ver-os", self.device_ver),
            ("x-device-model", self.device_model),
        ):
            if value:
                headers[header] = value

        headers.update(self.extra_headers)
        return headers


class UpstreamError(RuntimeError):
    pass


class UpstreamFetcher:
    """One shared connection pool for every upstream panel."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client = httpx.AsyncClient(
            timeout=httpx.Timeout(settings.upstream_timeout),
            follow_redirects=True,
            verify=settings.upstream_verify_tls,
            proxy=settings.upstream_proxy,
            limits=httpx.Limits(max_connections=50, max_keepalive_connections=20),
            headers={},
        )

    async def aclose(self) -> None:
        await self._client.aclose()

    async def fetch(self, request: UpstreamRequest) -> UpstreamResult:
        headers = request.build_headers()
        started = time.perf_counter()
        try:
            response = await self._client.get(request.url, headers=headers)
        except httpx.HTTPError as exc:
            raise UpstreamError(f"не удалось получить подписку: {exc}") from exc
        elapsed_ms = int((time.perf_counter() - started) * 1000)

        content = response.content
        if len(content) > self._settings.upstream_max_bytes:
            raise UpstreamError(
                f"ответ апстрима слишком большой: {len(content)} байт "
                f"(лимит {self._settings.upstream_max_bytes})"
            )

        encoding = response.encoding or "utf-8"
        try:
            text = content.decode(encoding, errors="replace")
        except LookupError:
            text = content.decode("utf-8", errors="replace")

        return UpstreamResult(
            status_code=response.status_code,
            text=text,
            headers={k.lower(): v for k, v in response.headers.items()},
            elapsed_ms=elapsed_ms,
            content_type=response.headers.get("content-type", ""),
            bytes_in=len(content),
        )


def passthrough_response_headers(upstream_headers: dict[str, str]) -> dict[str, str]:
    return {
        name: upstream_headers[name]
        for name in FORWARD_RESPONSE_HEADERS
        if name in upstream_headers
    }
